### ISSUE TITLE
The error message is not clear

### ISSUE THREAD

**Issue by jaywcjlove** [kktjs/npm-publish#1]
<img width="399" alt="image" src="https://user-images.githubusercontent.com/1680273/187212346-8ab98cec-1b68-460b-b564-61d10e81846e.png">

**Comment by SunLxy** [comment]
@jaywcjlove  这个是由[@jsdevtools/npm-publish](https://github.com/JS-DevTools/npm-publish/blob/e42e3720bfe21259120218c19fdbfedcf72692bd/src/npm-config.ts#L95-L105)依赖包抛出的错误

**Comment by jaywcjlove** [comment]
@SunLxy 怎么解决？

**Comment by SunLxy** [comment]
@jaywcjlove  测试了一下，这个是一次发布包超过55个造成的。暂时没有解决的

**Comment by SunLxy** [comment]
@jaywcjlove 调整了一下循环调用发布方法，可以发布多个[ci案例](https://github.com/SunLxy/github-ci-test/runs/8086088731?check_suite_focus=true#step:7:11)

**Comment by jaywcjlove** [comment]
https://www.npmjs.com/package/libnpmpublish

我差点用官方包给你重构了 :)
